CREATE TABLE IF NOT EXISTS node(
id BIGINT PRIMARY KEY NOT NULL,
latitude DOUBLE NOT NULL,
longitude DOUBLE NOT NULL);

CREATE TABLE IF NOT EXISTS node_tag(
id BIGINT NOT NULL,
tag_key VARCHAR(255) NOT NULL,
tag_value VARCHAR(255),
PRIMARY KEY (id, tag_key),
FOREIGN KEY(id) REFERENCES node(id) ON DELETE CASCADE ON UPDATE CASCADE );

CREATE TABLE IF NOT EXISTS way(
id BIGINT PRIMARY KEY NOT NULL );

CREATE TABLE IF NOT EXISTS way_tag(
id BIGINT NOT NULL,
tag_key VARCHAR(255) NOT NULL,
tag_value VARCHAR(255),
PRIMARY KEY (id, tag_key),
FOREIGN KEY(id) REFERENCES way(id) ON DELETE CASCADE ON UPDATE CASCADE );

CREATE TABLE IF NOT EXISTS way_node(
way_id BIGINT NOT NULL,
order_in_way INT NOT NULL,
node_id BIGINT NOT NULL,
PRIMARY KEY(way_id, order_in_way),
FOREIGN KEY(way_id) REFERENCES way(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(node_id) REFERENCES node(id) ON DELETE CASCADE ON UPDATE CASCADE );
